name: Run Tests
on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel--composer-${{ hashFiles('**/composer.lock') }}

      - name: Install PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          tools: prestissimo
          extensions: pdo, sqlite, pdo_sqlite

      - name: Install Dependencies
        run: composer install

      - name: Setup Application
        run: |
          cp .env.example .env
          php artisan key:generate

      - name: Run Tests
        run: php artisan test

      - name: Trigger Envoyer Deploy
        uses: wei/curl@v1
        with:
          args: ${{secrets.ENVOYER_DEPLOY_URL}}
